### ISSUE TITLE
Size of dataset

### ISSUE THREAD

**Issue by Shree3245** [undercoverGod/lossy-image-compression#1]
How large was your dataset, to be able to decompress almost perfectly? when I try to train with my own dataset I get something that looks like this :
![image](https://user-images.githubusercontent.com/25982839/120926989-d99dfc80-c6fc-11eb-918d-87c80a7a828e.png)
I did not change your code at all, just an issue with training.
I am only assuming it is the problem of the dataset training and nothing else as I have not changed anything else

**Comment by ibrahimali123** [comment]
@Shree3245 did you know the answer ? I want to get a better decompression image to be like very near to original, so what should I do?

**Comment by zvezdochiot** [comment]
Hi @ibrahimali123 .

See https://github.com/ilyakurdyukov/jpeg-quantsmooth

**Comment by abskj** [comment]
Hi @Shree3245  @ibrahimali123  sorry i had missed this earlier, I used div2K dataset (https://data.vision.ee.ethz.ch/cvl/DIV2K/)  which had 800 very high quality images. With that I used dataset called mobile photos(they were captured with mobile) for which I can't find the link right now. It had 1000+ images. So I would recommend 2000 images for at least getting quality like existing.

**Comment by ibrahimali123** [comment]
Thanks @abskj for your reply

**Comment by ibrahimali123** [comment]
![Screenshot from 2022-09-24 11-23-17](https://user-images.githubusercontent.com/8504784/192090597-e61449c9-7d54-4848-8010-e70f4c9d08c6.png)

@abskj For this encoder part of the autoencoder, I can say that the encoder use 2 hidden layers, right? in master branch autoencoder.py

**Comment by ibrahimali123** [comment]
and in model 2 branch, the model use 3 number of hidden layers, right ?

**Comment by ibrahimali123** [comment]
I am just want know how many hidden layers used in this model

**Comment by abskj** [comment]
Yes 2 hidden layers.. each layer having (conv, relu and batch norm)
