### ISSUE TITLE
I need to train the model to got de-compressed images near the original with better quality how can I do that ? which params needs to change?

### ISSUE THREAD

**Issue by ibrahimali123** [undercoverGod/lossy-image-compression#2]
I need to train the model to got de-compressed images near the original with better quality how can I do that ? which params needs to change?

**Comment by abskj** [comment]
Hi @ibrahimali123  I think the encoder/decoder created here is quite simple with very less params, so amount of techniques it can learn is limited. So what I would recommend is increase model params by maybe adding more layers or something. Model is at (https://github.com/abskj/lossy-image-compression/blob/master/model/autoencoder.py) . Then you need to train more on as large a dataset as possible and as diverse as possible. With the usual hyper params tweaking you need to train to fullest and not overfit. Thats all. I realize this is general advice so if you have any specific question please let me know.
